### ISSUE TITLE
TweetnaclCrypto

### ISSUE THREAD

**Issue by Krutifulmen** [LkPrtctrd/BSL-V53#3]
i installed TweetnaclCrypto, but it saying modulenotfound: _tweetnacl. how to fix?

**Comment by LkPrtctrd** [comment]
idk

**Comment by Krutifulmen** [comment]
how you fixed it?

**Comment by Krutifulmen** [comment]
it work on your computer?

**Comment by LkPrtctrd** [comment]
i didn't have that problem

**Comment by LkPrtctrd** [comment]
check if you installed tweetnacl correctly

**Comment by Krutifulmen** [comment]
ты рус? anyway, how to correct?

**Comment by LkPrtctrd** [comment]
Да. Не знаю как исправить, так как я даже не знаю, какая у тебя ошибка. Можешь отправить скриншот с установки?

**Comment by Krutifulmen** [comment]
> Да. Не знаю как исправить, так как я даже не знаю, какая у тебя ошибка. Можешь отправить скриншот с установки?

давай я тебе лог дам установки

**Comment by LkPrtctrd** [comment]
Давай

**Comment by Krutifulmen** [comment]
во

C:\Users\Dmitr\AppData\Local\Programs\Python\Python311\Lib\site-packages\setuptools\_distutils\cmd.py:66: SetuptoolsDeprecationWarning: setup.py install is deprecated.
!!

        ********************************************************************************
        Please avoid running ``setup.py`` directly.
        Instead, use pypa/build, pypa/installer or other
        standards-based tools.

        See https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html for details.
        ********************************************************************************

!!
  self.initialize_options()
C:\Users\Dmitr\AppData\Local\Programs\Python\Python311\Lib\site-packages\setuptools\_distutils\cmd.py:66: EasyInstallDeprecationWarning: easy_install command is deprecated.
!!

        ********************************************************************************
        Please avoid running ``setup.py`` and ``easy_install``.
        Instead, use pypa/build, pypa/installer or other
        standards-based tools.

        See https://github.com/pypa/setuptools/issues/917 for details.
        ********************************************************************************

!!
  self.initialize_options()
cl: командная строка warning D9002: пропуск неизвестного параметра "-funroll-loops"
cl: командная строка warning D9002: пропуск неизвестного параметра "-fomit-frame-pointer"
randombytes.c
randombytes.c(67): warning C4244: функция: преобразование "__int64" в "DWORD", возможна потеря данных
Using Windows cryptographic API
cl: командная строка warning D9002: пропуск неизвестного параметра "-funroll-loops"
cl: командная строка warning D9002: пропуск неизвестного параметра "-fomit-frame-pointer"
tweetnacl.c
tweetnacl.c(45): warning C4244: =: преобразование "u32" в "u8", возможна потеря данных
tweetnacl.c(51): warning C4244: =: преобразование "u64" в "u8", возможна потеря данных
tweetnacl.c(57): warning C4018: <: несоответствие типов со знаком и без знака
tweetnacl.c(138): warning C4244: =: преобразование "u32" в "u8", возможна потеря данных
tweetnacl.c(228): warning C4146: применение унарного минуса к типу без знака; результат оставлен без знака
tweetnacl.c(234): warning C4244: =: преобразование "u32" в "u8", возможна потеря данных
tweetnacl.c(316): warning C4244: =: преобразование "i64" в "u8", возможна потеря данных
tweetnacl.c(410): warning C4244: функция: преобразование "i64" в "int", возможна потеря данных
tweetnacl.c(411): warning C4244: функция: преобразование "i64" в "int", возможна потеря данных
tweetnacl.c(430): warning C4244: функция: преобразование "i64" в "int", возможна потеря данных
tweetnacl.c(431): warning C4244: функция: преобразование "i64" в "int", возможна потеря данных
tweetnacl.c(548): warning C4244: return: преобразование "u64" в "int", возможна потеря данных
tweetnacl.c(723): warning C4018: <: несоответствие типов со знаком и без знака
cl: командная строка warning D9002: пропуск неизвестного параметра "-funroll-loops"
cl: командная строка warning D9002: пропуск неизвестного параметра "-fomit-frame-pointer"
tweetnaclmodule.c
tweetnaclmodule.c(590): warning C4018: <: несоответствие типов со знаком и без знака
tweetnaclmodule.c(649): warning C4018: <: несоответствие типов со знаком и без знака
tweetnaclmodule.c(720): warning C4018: <: несоответствие типов со знаком и без знака
tweetnaclmodule.c(782): warning C4018: <: несоответствие типов со знаком и без знака
tweetnaclmodule.c(930): warning C4018: <: несоответствие типов со знаком и без знака
tweetnaclmodule.c(989): warning C4018: <: несоответствие типов со знаком и без знака
tweetnaclmodule.c(1115): warning C4101: dummy: неиспользованная локальная переменная
   Создается библиотека build\temp.win-amd64-cpython-311\Release\_tweetnacl.cp311-win_amd64.lib и объект build\temp.win-amd64-cpython-311\Release\_tweetnacl.cp311-win_amd64.exp
Создание кода
Создание кода завершено
zip_safe flag not set; analyzing archive contents...
__pycache__._tweetnacl.cpython-311: module references __file__

**Comment by Krutifulmen** [comment]
ну чо?

**Comment by LkPrtctrd** [comment]
В итоге он установился или нет? Покажи самый конец лога

**Comment by Krutifulmen** [comment]
это весь лог

**Comment by Krutifulmen** [comment]
это говорит пай чарм

Traceback (most recent call last):
  File "E:\Dmitr\Downloads\BSL-V53-main\BSL-V53-main\Main.py", line 4, in <module>
    from Heart.Connection import Connection
  File "E:\Dmitr\Downloads\BSL-V53-main\BSL-V53-main\Heart\Connection.py", line 9, in <module>
    from Heart.Crypto import Crypto 
  File "E:\Dmitr\Downloads\BSL-V53-main\BSL-V53-main\Heart\Crypto.py", line 3, in <module>
    from _tweetnacl import (crypto_box_beforenm, crypto_scalarmult_base, crypto_box_NONCEBYTES, crypto_secretbox, crypto_secretbox_open)
ModuleNotFoundError: No module named '_tweetnacl'

Process finished with exit code 1

**Comment by Krutifulmen** [comment]
если написать pip list то там есть этот модуль

**Comment by LkPrtctrd** [comment]
> это говорит пай чарм
> 
> Traceback (most recent call last): File "E:\Dmitr\Downloads\BSL-V53-main\BSL-V53-main\Main.py", line 4, in from Heart.Connection import Connection File "E:\Dmitr\Downloads\BSL-V53-main\BSL-V53-main\Heart\Connection.py", line 9, in from Heart.Crypto import Crypto File "E:\Dmitr\Downloads\BSL-V53-main\BSL-V53-main\Heart\Crypto.py", line 3, in from _tweetnacl import (crypto_box_beforenm, crypto_scalarmult_base, crypto_box_NONCEBYTES, crypto_secretbox, crypto_secretbox_open) ModuleNotFoundError: No module named '_tweetnacl'
> 
> Process finished with exit code 1

Запускай не из пайчарма или других каких-то программ, а также через консоль

**Comment by Krutifulmen** [comment]
ок ща

**Comment by Krutifulmen** [comment]
СПС ОГРОМНОЕ ИЗ КМДЭШКИ РАБОТАЕТ!!!!

**Comment by LkPrtctrd** [comment]
> СПС ОГРОМНОЕ ИЗ КМДЭШКИ РАБОТАЕТ!!!!
👌

**Comment by Krutifulmen** [comment]
короч, после модифицирования апк, он не хочет устанавливаться. пакет поврежден. че делать

**Comment by LkPrtctrd** [comment]
Этот вопрос уже не ко мне, решайте сами, пробуйте другой метод изменения и подписи .apk файла.

**Comment by Krutifulmen** [comment]
> Этот вопрос уже не ко мне, решайте сами, пробуйте другой метод изменения и подписи .apk файла.

ок. спасибо.

**Comment by Krutifulmen** [comment]
все работает. спс. как добавить акцию?
